spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youn?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:  root
    password:  qorghska12!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
